ExpenseManager/Controllers/CategoryController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using ExpenseManager.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

        public CategoryController(ICategoryService cService)
        {
            _categoryService = cService;
        }

        // GET: Category
        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        public async Task<ActionResult> List()
        {
            var categories = await _categoryService.GetAllAsync();
            return View(categories);
        }

        // GET: Category/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var category = await _categoryService.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CategoryModel model)
        {
            try
            {
                var category = await _categoryService.CreateAsync(model.Adapt<CategoryDto>());
                if (category == null)
                {
                    return View("CustomError", "Create failed");
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("Name", "A category with this name already exists.");
                return View(model);
            }
        }

        // GET: Category/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var category = await _categoryService.GetByIdAsync(id);
            if (category == null)
            {
                return NotFound(id);
            }
            return View(category.Adapt<CategoryModel>());
        }

        // POST: Category/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, CategoryModel model)
        {
            try
            {
                var category = await _categoryService.UpdateAsync(id, model.Adapt<CategoryDto>());
                if (category == null)
                {
                    return View("CustomError", "Edit failed");
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ModelState.AddModelError("Name", "A category with this name already exists.");
                return View(model);
            }
        }

        // GET: Category/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var transaction = await _categoryService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            return View(id);
        }

        // POST: TransactionController/DeleteConfirm/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            try
            {
                var res = await _categoryService.DeleteAsync(id);
                if (!res)
                {
                    return StatusCode(400);
                }
                return RedirectToAction("List");
            }
            catch
            {
                return View("CustomError", "Cannot delete because of references");
            }
        }
    }
}

ExpenseManager/Controllers/CustomErrorController.cs
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    [Route("Error")]
    public class CustomErrorController : Controller
    {
        public IActionResult Index()
        {
            return View("CustomError", "An error occurred. Please try again later.");
        }
    }
}

ExpenseManager/Controllers/DashboardController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using ExpenseManager.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    [Authorize]
    public class DashboardController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly UserManager<User> _userManager;

        public DashboardController(ITransactionService tService, UserManager<User> userManager)
        {
            _transactionService = tService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }
            var options = new FilterOptionsDto { UserId = user.Id, };
            var transactions = await _transactionService.GetAllByOptionsAsync(options);
            var model = CreateDashboardModel(transactions);

            return View(model);
        }

        private DashboardViewModel CreateDashboardModel(List<TransactionViewDto> transactions)
        {
            var income = transactions
                .Where(t => t.TransactionType == TransactionType.Income)
                .Sum(t => t.Amount);
            var expense = transactions
                .Where(t => t.TransactionType == TransactionType.Expense)
                .Sum(t => t.Amount);
            var vendorName = transactions
                .Select(t => t.Vendor?.Name)
                .GroupBy(name => name)
                .OrderByDescending(g => g.Count())
                .Select(g => g.Key)
                .FirstOrDefault();
            var categoryName = transactions
                .SelectMany(t => t.Categories)
                .GroupBy(c => c.Name)
                .OrderByDescending(g => g.Count())
                .Select(g => g.Key)
                .FirstOrDefault();
            var model = new DashboardViewModel
            {
                TotalIncome = income,
                TotalExpense = expense,
                Balance = income - expense,
                NumberOfTransactions = transactions.Count,
                VendorName = vendorName ?? "None",
                CategoryName = categoryName ?? "None"
            };
            return model;
        }
    }
}

ExpenseManager/Controllers/GraphController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    public enum TimeRange
    {
        AllTime,
        LastYear,
        LastMonth,
        LastDay
    }

    [Authorize]
    public class GraphController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly UserManager<User> _userManager;

        public GraphController(ITransactionService tService, UserManager<User> userManager)
        {
            _transactionService = tService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(
            FilterOptionsDto? options = null,
            TimeRange? timeRange = null
        )
        {
            var user = await _userManager.GetUserAsync(User);
            options ??= new FilterOptionsDto();
            options.UserId = user!.Id;

            DateTime? startDate;

            switch (timeRange)
            {
                case TimeRange.LastYear:
                    startDate = DateTime.Now.AddYears(-1);
                    break;
                case TimeRange.LastMonth:
                    startDate = DateTime.Now.AddMonths(-1);
                    break;
                case TimeRange.LastDay:
                    startDate = DateTime.Now.AddDays(-1);
                    break;
                default:
                    startDate = null;
                    break;
            }
            options.From ??= startDate;
            var transactions = await _transactionService.GetAllByOptionsAsync(options);

            ViewBag.SelectedTimeRange = timeRange;
            return View(transactions);
        }
    }
}

ExpenseManager/Controllers/TransactionController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using ExpenseManager.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExpenseManager.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly IVendorService _vendorService;
        private readonly ICategoryService _categoryService;
        private readonly UserManager<User> _userManager;

        public TransactionController(
            ITransactionService tService,
            IVendorService vService,
            ICategoryService cService,
            UserManager<User> userManager
        )
        {
            _transactionService = tService;
            _vendorService = vService;
            _categoryService = cService;
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: TransactionController/List
        public async Task<ActionResult> List(FilterOptionsDto options)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }
            options.UserId = user.Id;

            var transactions = await _transactionService.GetAllByOptionsAsync(options);

            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            return View(
                new FilterViewModel { FilterOptions = options, Transactions = transactions }
            );
        }

        // GET: TransactionController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            if (!(await UserIdMatch(transaction.UserId)))
            {
                return Unauthorized();
            }
            return View(transaction);
        }

        // GET: TransactionController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            return View();
        }

        // POST: TransactionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TransactionChangeDto model)
        {
            try
            {
                model.Description ??= "";
                if (ModelState.IsValid)
                {
                    var transactionDto = model;

                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return Unauthorized();
                    }
                    transactionDto.UserId = user.Id;
                    var res = await _transactionService.CreateAsync(transactionDto);
                    if (res == null)
                    {
                        return StatusCode(500);
                    }
                    return RedirectToAction("List");
                }
                ViewBag.Vendors = await GetVendorsOptions();
                ViewBag.Categories = await GetCategoriesOptions();
                return View(model);
            }
            catch
            {
                return StatusCode(500);
            }
        }

        // GET: TransactionController/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            var viewDto = (TransactionViewDto)transaction;
            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            var model = viewDto.Adapt<TransactionChangeDto>();
            model.CategoriesIds = viewDto.Categories.Select(c => c.Id).ToList();
            model.VendorId = viewDto.Vendor?.Id ?? 0;
            return View(model);
        }

        // POST: TransactionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, TransactionChangeDto model)
        {
            model.Description ??= "";
            if (!ModelState.IsValid)
            {
                ViewBag.Vendors = await GetVendorsOptions();
                ViewBag.Categories = await GetCategoriesOptions();
                return View(model);
            }

            await _transactionService.UpdateAsync(id, model);

            return RedirectToAction("Details", new { id });
        }

        // GET: TransactionController/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            if (!await UserIdMatch(((TransactionViewDto)transaction).UserId))
            {
                return Unauthorized();
            }
            return View(id);
        }

        // POST: TransactionController/DeleteConfirm/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            try
            {
                var res = await _transactionService.DeleteAsync(id);
                if (!res)
                {
                    return StatusCode(400);
                }
                return RedirectToAction("List");
            }
            catch
            {
                return View("CustomError", "Cannot delete because of references");
            }
        }

        private async Task<bool> UserIdMatch(int userId)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return false;
            }
            return user.Id == userId;
        }

        private async Task<IEnumerable<SelectListItem>?> GetVendorsOptions()
        {
            return (await _vendorService.GetAllAsync()).Select(v => new SelectListItem
            {
                Value = v.Id.ToString(),
                Text = v.Name
            });
        }

        private async Task<IEnumerable<SelectListItem>?> GetCategoriesOptions()
        {
            return (await _categoryService.GetAllAsync()).Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            });
        }
    }
}

ExpenseManager/Views/Shared/CustomError.cshtml
@model string
@{
    ViewData["Title"] = "Custom Error";
}

<h1>Error</h1>

<p>@Model</p>

ExpenseManager/Views/Shared/Delete.cshtml
@model int
<h1>Delete</h1>

<h4>Are you sure you want to delete?</h4>
<div>
    <form asp-action="DeleteConfirm" method="post">
        <input type="hidden" name="id" value="@Model" />
        <div class="form-group">
            <input type="submit" value="Delete" class="btn btn-danger" />
            <a asp-action="Index" class="btn btn-default">Back to List</a>
        </div>
    </form>
</div>

ExpenseManager/Views/Shared/_Layout.cshtml
@using DataAccessLayer.Entities
@using Microsoft.AspNetCore.Identity
@inject UserManager<User> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpenseManager.styles.css" asp-append-version="true" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ExpenseManager</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @{
                            var user = await UserManager.GetUserAsync(User);
                        }
                        @if (user != null)
                        {
                            var roles = await UserManager.GetRolesAsync(user);
                            <li>
                                <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="nav-link text-dark">Dashboard</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Transaction" asp-action="List" class="nav-link text-dark">Transaction History</a>
                            </li>

                            if (roles.Contains("Admin"))
                            {
                                <li>
                                    <a asp-area="" asp-controller="Category" asp-action="List" class="nav-link text-dark">Categories</a>
                                </li>
                            }
                            <li>
                                <a asp-area="" asp-controller="Graph" asp-action="Index" class="nav-link text-dark">Graph</a>
                            </li>
                            <li>
                                <a asp-area="" asp-controller="Transaction" asp-action="List" class="nav-link text-dark">@user.Email</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark right-aligned-list-item" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                            </li>
                        }
                        else
                        {
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                            <li>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ExpenseManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>