ExpenseManager/Controllers/GraphController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    public enum TimeRange
    {
        AllTime,
        LastYear,
        LastMonth,
        LastDay
    }

    [Authorize]
    public class GraphController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly UserManager<User> _userManager;

        public GraphController(ITransactionService tService, UserManager<User> userManager)
        {
            _transactionService = tService;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index(
            FilterOptionsDto? options = null,
            TimeRange? timeRange = null
        )
        {
            var user = await _userManager.GetUserAsync(User);
            options ??= new FilterOptionsDto();
            options.UserId = user!.Id;

            DateTime? startDate;

            switch (timeRange)
            {
                case TimeRange.LastYear:
                    startDate = DateTime.Now.AddYears(-1);
                    break;
                case TimeRange.LastMonth:
                    startDate = DateTime.Now.AddMonths(-1);
                    break;
                case TimeRange.LastDay:
                    startDate = DateTime.Now.AddDays(-1);
                    break;
                default:
                    startDate = null;
                    break;
            }
            options.From ??= startDate;
            var transactions = await _transactionService.GetAllByOptionsAsync(options);

            ViewBag.SelectedTimeRange = timeRange;
            return View(transactions);
        }
    }
}

ExpenseManager/Controllers/TransactionController.cs
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using ExpenseManager.Models;
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ExpenseManager.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly IVendorService _vendorService;
        private readonly ICategoryService _categoryService;
        private readonly UserManager<User> _userManager;

        public TransactionController(
            ITransactionService tService,
            IVendorService vService,
            ICategoryService cService,
            UserManager<User> userManager
        )
        {
            _transactionService = tService;
            _vendorService = vService;
            _categoryService = cService;
            _userManager = userManager;
        }

        public ActionResult Index()
        {
            return RedirectToAction("List");
        }

        // GET: TransactionController/List
        public async Task<ActionResult> List(FilterOptionsDto options)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Unauthorized();
            }
            options.UserId = user.Id;

            var transactions = await _transactionService.GetAllByOptionsAsync(options);

            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            return View(
                new FilterViewModel { FilterOptions = options, Transactions = transactions }
            );
        }

        // GET: TransactionController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            if (!(await UserIdMatch(transaction.UserId)))
            {
                return Unauthorized();
            }
            return View(transaction);
        }

        // GET: TransactionController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            return View();
        }

        // POST: TransactionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(TransactionChangeDto model)
        {
            try
            {
                model.Description ??= "";
                if (ModelState.IsValid)
                {
                    var transactionDto = model;

                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return Unauthorized();
                    }
                    transactionDto.UserId = user.Id;
                    var res = await _transactionService.CreateAsync(transactionDto);
                    if (res == null)
                    {
                        return StatusCode(500);
                    }
                    return RedirectToAction("List");
                }
                ViewBag.Vendors = await GetVendorsOptions();
                ViewBag.Categories = await GetCategoriesOptions();
                return View(model);
            }
            catch
            {
                return StatusCode(500);
            }
        }

        // GET: TransactionController/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            var viewDto = (TransactionViewDto)transaction;
            ViewBag.Vendors = await GetVendorsOptions();
            ViewBag.Categories = await GetCategoriesOptions();
            var model = viewDto.Adapt<TransactionChangeDto>();
            model.CategoriesIds = viewDto.Categories.Select(c => c.Id).ToList();
            model.VendorId = viewDto.Vendor?.Id ?? 0;
            return View(model);
        }

        // POST: TransactionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, TransactionChangeDto model)
        {
            model.Description ??= "";
            if (!ModelState.IsValid)
            {
                ViewBag.Vendors = await GetVendorsOptions();
                ViewBag.Categories = await GetCategoriesOptions();
                return View(model);
            }

            await _transactionService.UpdateAsync(id, model);

            return RedirectToAction("Details", new { id });
        }

        // GET: TransactionController/Delete/5
        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            var transaction = await _transactionService.GetByIdAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            if (!await UserIdMatch(((TransactionViewDto)transaction).UserId))
            {
                return Unauthorized();
            }
            return View(id);
        }

        // POST: TransactionController/DeleteConfirm/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirm(int id)
        {
            try
            {
                var res = await _transactionService.DeleteAsync(id);
                if (!res)
                {
                    return StatusCode(400);
                }
                return RedirectToAction("List");
            }
            catch
            {
                return View("CustomError", "Cannot delete because of references");
            }
        }

        private async Task<bool> UserIdMatch(int userId)
        {
            var user = await _userManager.GetUserAsync(User);

            if (user == null)
            {
                return false;
            }
            return user.Id == userId;
        }

        private async Task<IEnumerable<SelectListItem>?> GetVendorsOptions()
        {
            return (await _vendorService.GetAllAsync()).Select(v => new SelectListItem
            {
                Value = v.Id.ToString(),
                Text = v.Name
            });
        }

        private async Task<IEnumerable<SelectListItem>?> GetCategoriesOptions()
        {
            return (await _categoryService.GetAllAsync()).Select(c => new SelectListItem
            {
                Value = c.Id.ToString(),
                Text = c.Name
            });
        }
    }
}

ExpenseManager/Controllers/TransferController.cs
using System.Text;
using System.Text.Json;
using BusinessLayer.Models;
using BusinessLayer.Services.Interfaces;
using DataAccessLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ExpenseManager.Controllers
{
    [Authorize]
    public class TransferController : Controller
    {
        private readonly ITransactionService _transactionService;
        private readonly UserManager<User> _userManager;
        private readonly ILogger<TransferController> _logger;

        public TransferController(
            ITransactionService tService,
            UserManager<User> userManager,
            ILogger<TransferController> logger
        )
        {
            _transactionService = tService;
            _userManager = userManager;
            _logger = logger;
        }

        [HttpGet]
        public async Task<IActionResult> Export(FilterOptionsDto? options)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                options ??= new FilterOptionsDto();
                options.UserId = user!.Id;
                var transactions = await _transactionService.GetAllByOptionsAsync(options);

                var json = JsonSerializer.Serialize(transactions);

                var fileName = "transactions.json";
                return File(Encoding.UTF8.GetBytes(json), "application/json", fileName);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return View("CustomError", "File export failed.");
            }
        }

        [HttpGet]
        public IActionResult Import()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Import(IFormFile file)
        {
            try
            {
                if (file != null && file.Length > 0)
                {
                    var user = await _userManager.GetUserAsync(User);
                    if (user == null)
                    {
                        return View("CustomError", "User not logged in");
                    }
                    var (success, message) = await _transactionService.ImportTransactions(
                        file,
                        user
                    );
                    if (!success)
                    {
                        return View("CustomError", message);
                    }
                    return RedirectToAction("List", "Transaction");
                }
                return View("CustomError", "File upload failed.");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, ex.Message);
                return View("CustomError", "File upload failed.");
            }
        }
    }
}

ExpenseManager/Views/Transaction/Create.cshtml
@using DataAccessLayer.Entities
@model BusinessLayer.Models.TransactionChangeDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control"  />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control"/>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionType" class="control-label"></label>
                <select asp-for="TransactionType" class="form-control">
                    @foreach (var value in Enum.GetValues(typeof(TransactionType)))
                    {
                        <option value="@value">@value</option>
                    }
                </select>
                <span asp-validation-for="TransactionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionFrequency" class="control-label"></label>
                <select asp-for="TransactionFrequency" class="form-control">
                    @foreach (var value in Enum.GetValues(typeof(TransactionFrequency)))
                    {
                        <option value="@value">@value</option>
                    }
                </select>
                <span asp-validation-for="TransactionFrequency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorId" class="control-label">Vendor</label>
                <select asp-for="VendorId" class="form-control">
                    @foreach (var vendor in ViewBag.Vendors)
                    {
                        <option value="@vendor.Value">@vendor.Text</option>
                    }
                </select>
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="category-section">
                    Categories
                    <div class="checkboxes" style="height: 6em; overflow-y: auto;">
                        @foreach (var category in ViewBag.Categories)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="CategoriesIds" value="@category.Value" />
                                    @category.Text
                                </label>
                            </div>
                        }
                    </div>
                    <span asp-validation-for="CategoriesIds" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

ExpenseManager/Views/Transaction/Details.cshtml
@model BusinessLayer.Models.TransactionViewDto

@{
    ViewData["Title"] = "Detail";
}

<h1>Detail</h1>

<div>
    <h4>Transaction</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactionType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionFrequency)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactionFrequency)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Vendor)
        </dt>
        <dd class = "col-sm-10">
            @{
                var vendorName = Model.Vendor != null ? Model.Vendor.Name : "Unknown";
            }
            @Html.DisplayFor(model => vendorName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Categories)
        </dt>
        <dd class="col-sm-10">
            @foreach (var category in Model.Categories!)
            {
                @Html.DisplayFor(modelItem => category.Name)
                @Html.Raw(" ")
            }
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="List">Back to List</a>
</div>

ExpenseManager/Views/Transaction/Edit.cshtml
@using DataAccessLayer.Entities
@model BusinessLayer.Models.TransactionChangeDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Transaction</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionType" class="control-label"></label>
                <select asp-for="TransactionType" class="form-control">
                    @foreach (var value in Enum.GetValues(typeof(TransactionType)))
                    {
                        <option value="@value">@value</option>
                    }
                </select>
                <span asp-validation-for="TransactionType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TransactionFrequency" class="control-label"></label>
                <input asp-for="TransactionFrequency" class="form-control" readonly />
                <span asp-validation-for="TransactionFrequency" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="VendorId" class="control-label">Vendor</label>
                <select asp-for="VendorId" class="form-control">
                    @foreach (var vendor in ViewBag.Vendors)
                    {
                        <option value="@vendor.Value">@vendor.Text</option>
                    }
                </select>
                <span asp-validation-for="VendorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="category-section">
                    Categories
                    <div class="checkboxes" style="height: 6em; overflow-y: auto;">
                        @foreach (var category in ViewBag.Categories)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="CategoriesIds" value="@category.Value" @(Model.CategoriesIds != null && Model.CategoriesIds.Contains(int.Parse(category.Value)) ? "checked" : "") />
                                    @category.Text
                                </label>
                            </div>
                        }
                    </div>
                    <span asp-validation-for="CategoriesIds" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="List">Back to List</a>
</div>

ExpenseManager/Views/Transaction/List.cshtml
@model FilterViewModel

@{
    ViewData["Title"] = "List";
    var transactions = Model.Transactions;
    var options = Model.FilterOptions;
}

<h1>Transactions</h1>
<div class="row">
    <div class="col-auto">
    <form method="get" action="@Url.Action("Create")">
        <button type="submit" class="btn btn-primary" style="margin-top: 10px;">Create New</button>
    </form>
    </div>
    
    <div class="col-auto">
    <form method="get" asp-controller="Transfer" asp-action="Import">
        <button type="submit" style="margin-top: 10px;" class="btn btn-primary">Import</button>
    </form>
    </div>
</div>


<form method="get" asp-action="List">
    <hr />
    <div class="row" style="margin-bottom: 17px;">
        <div class="col-md-2 text-center">
            <label for="lowerLimit">Lower Limit:</label>
            <input type="number" id="lowerLimit" name="lowerLimit" value="@Model.FilterOptions.LowerLimit" />
        </div>

        <div class="col-md-2 text-center">
            <label for="upperLimit">Upper Limit:</label>
            <input type="number" id="upperLimit" name="upperLimit" value="@Model.FilterOptions.UpperLimit" />
        </div>
            
        <div class="col-md-1" style="margin-bottom: 7px; margin-top: 10px;">
            <label>
                @Html.CheckBox("Income", Model.FilterOptions.Income)
                Incomes
            </label>

            <label>
                @Html.CheckBox("Expense", Model.FilterOptions.Expense)
                Expenses
            </label>
        </div>

        <div class="col-md-2 text-center">
            <label for="fromDate">From:</label>
            <input type="date" id="fromDate" name="from" value="@Model.FilterOptions.From?.ToString("yyyy-MM-dd")" class="form-control" />
        </div>

        <div class="col-md-2 text-center">
            <label for="toDate">To:</label>
            <input type="date" id="to" name="to" value="@Model.FilterOptions.To?.ToString("yyyy-MM-dd")" class="form-control" />
        </div>
        <div class="col-md-1 text-center">
            <button type="submit" style="margin-top: 20px;" class="btn btn-primary">Filter</button>
        </div>
        <div class="col-md-1 text-center">
            <button type="submit" class="btn btn-primary" style="margin-top: 20px;" formaction="@Url.Action("Export", "Transfer")">Export</button>
        </div>
        <div class="col-md-1 text-center">
            <button type="submit" class="btn btn-primary" style="margin-top: 20px;" formaction="@Url.Action("Index", "Graph")">Graph</button>
        </div>

        
    </div>
        

<div class="row">
    <!-- Table Column -->
    <div class="col-md-10">
<table class="table">
    <thead>
        <tr>
            <th>
                Amount
            </th>
            <th>
                Description
            </th>
            <th>
                Type
            </th>
            <th>
                Frequency
            </th>
            <th>
                CreatedAt
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in transactions)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td style="max-width: 200px; overflow-y: auto;">
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
@{
string textColor = item.TransactionType.ToString() == "Income" ? "green" : "red";
}
                <div style="color: @textColor; font-weight: bold;">
                    @Html.DisplayFor(modelItem => item.TransactionType)
                <div />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TransactionFrequency)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
</div>
            <div class="col-md-2">
                <div class="category-section">
                    Categories
                    <div class="checkboxes" style="height: 6em; overflow-y: auto;">
                        @foreach (var category in ViewBag.Categories)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="CategoryIds" value="@category.Value" @(Model.FilterOptions.CategoryIds != null && Model.FilterOptions.CategoryIds.Contains(int.Parse(category.Value)) ? "checked" : "") />
                                    @category.Text
                                </label>
                            </div>
                        }
                    </div>
                </div>
            
                <div class="vendor-section" style="padding-top: 10px;">
                    Vendors
                    <div class="checkboxes" style="height: 6em; overflow-y: auto;">
                        @foreach (var vendor in ViewBag.Vendors)
                        {
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" name="VendorIds" value="@vendor.Value" @(Model.FilterOptions.VendorIds != null && Model.FilterOptions.VendorIds.Contains(int.Parse(vendor.Value)) ? "checked" : "") />
                                    @vendor.Text
                                </label>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    
</form>